add in check that symbolic link is not left behind

diff --git a/buildenv b/buildenv
--- a/buildenv
+++ b/buildenv
@@ -6,7 +6,14 @@ export ZOPEN_CONFIGURE="skip"
 export ZOPEN_MAKE="skip"
 export ZOPEN_CHECK="zopen_check"
 
+META_DEV_DIR="${PWD}/meta"
 if [ -z "${ZOPEN_META_DEV_ROOT}" ] ; then
+  if [ -d "${META_DEV_DIR}" ]; then
+    if [ -L "${META_DEV_DIR}" ]; then
+      echo "ZOPEN_META_DEV_ROOT is NOT set, but ${META_DEV_DIR} is a symbolic link. Either set ZOPEN_META_DEV_ROOT or remove the symbolic link"
+      return 8
+    fi
+  fi
   export ZOPEN_INSTALL="zopen_install"
 else
   export ZOPEN_INSTALL='skip'
@@ -24,22 +31,21 @@ else
     return 8
   fi
 
-  META_DIR="${PWD}/meta"
-  if [ -d "${META_DIR}" ]; then
-    if ! [ -L "${META_DIR}" ]; then
+  if [ -d "${META_DEV_DIR}" ]; then
+    if ! [ -L "${META_DEV_DIR}" ]; then
       # We may already have a git clone'd meta. If so, move the cloned tree to meta-cloned
-      mv "${META_DIR}" "${META_DIR}-cloned"
+      mv "${META_DEV_DIR}" "${META_DEV_DIR}-cloned"
     else
       # There may already be a symbolic link here - if so, delete it in case it is stale
-      rm "${META_DIR}"
+      rm "${META_DEV_DIR}"
     fi
   else
     # Directory has not yet been cloned - just have symbolic link created (next)
     :
   fi
       
-  if ! ln -s "${ZOPEN_META_DEV_ROOT}" "${META_DIR}" ; then
-    echo "Unable to create symbolic from from ${META_DIR} to ${ZOPEN_META_DEV_ROOT}" >&2
+  if ! ln -s "${ZOPEN_META_DEV_ROOT}" "${META_DEV_DIR}" ; then
+    echo "Unable to create symbolic from from ${META_DEV_DIR} to ${ZOPEN_META_DEV_ROOT}" >&2
     return 8
   fi
 fi
