Update buildenv
Good catch

Co-authored-by: Igor Todorovski <39890068+IgorTodorovskiIBM@users.noreply.github.com>

diff --git a/buildenv b/buildenv
--- a/buildenv
+++ b/buildenv
@@ -45,7 +45,7 @@ else
   fi
       
   if ! ln -s "${ZOPEN_META_DEV_ROOT}" "${META_DEV_DIR}" ; then
-    echo "Unable to create symbolic from from ${META_DEV_DIR} to ${ZOPEN_META_DEV_ROOT}" >&2
+    echo "Unable to create symbolic from ${META_DEV_DIR} to ${ZOPEN_META_DEV_ROOT}" >&2
     exit 8
   fi
 fi
