cleanup code now that "meta" has zopen --version support

diff --git a/buildenv b/buildenv
--- a/buildenv
+++ b/buildenv
@@ -66,7 +66,7 @@ zopen_get_version()
 {
   version=$(./bin/zopen --version 2>/dev/null)
   if [ $? -gt 0 ]; then
-    echo "1.0.1" # temporary - using an 'old' meta that does not support --version yet
+    echo "Internal Error. Unable to get version information from zopen --version" >&2
   else
     echo "${version}" | awk '{ print $2; }'
   fi
